CREATE PROC FI_SP_AltCliente
    @NOME          VARCHAR (50) ,
	@CPF		   VARCHAR (14),
	@Id            BIGINT,
	@IDCLIENTE	   BIGINT
AS
BEGIN
	UPDATE BENEFICIARIOS
	SET 
		NOME = @NOME, 
		CPF = @CPF
	WHERE Id = @Id AND IDCLIENTE = @IDCLIENTE
END