CREATE PROC FI_SP_ConsBeneficiario
	@ID			BIGINT,
	@IDCLIENTE	BIGINT
AS
BEGIN
	IF(@ID > 0)
		SELECT NOME, CPF, ID FROM [BENEFICIARIOS] WITH(NOLOCK) 
		WHERE [IDCLIENTE] = @IDCLIENTE AND [ID] = @ID
	ELSE
		SELECT NOME, CPF, ID FROM [BENEFICIARIOS] WITH(NOLOCK) WHERE [IDCLIENTE] = @IDCLIENTE
END